<?php defined('SYSPATH') OR die('No direct script access.');
/**
 * Base class for all of the container classes. Containers are components
 * that are able to hold child components.
 *
 * @package    Kohana/UI
 * @category   Extension
 * @author     Kohana Team
 * @copyright  (c) 2011-2012 Kohana Team
 * @license    http://kohanaphp.com/license
 */
class Kohana_UI_Container extends UI_Component {

    /**
     * @var  array  Holds child components.
     */
    protected $_items = array();

    /**
     * Attempts to add the passed class instance or generate string
     * as a child component.
     *
     * @param   mixed   If an instance of UI_Component is passed, we simply
     *                  add it to the '_items' array on this object. If
     *                  anything else is passed in, we forward the passed data
     *                  to the 'UI::generate' method and then attempt to add
     *                  the return value to the '_items' array.
     * @return  object  A reference to this class instance.
     */
    public function add($child)
    {
        // If the child is an instance of UI_Component
        if ($child instanceof UI_Component) {
            // Add it to the '_items' array
            $this->_items[] = $child;

            // Return a reference to this class instance
            return $this;
        }

        // If the passed child data is an object
        if (is_object($child)) {
            // Attempt to add the result of the call to 'UI::generate'
            $this->add(UI::generate($child));

            // Return a reference to this class instance
            return $this;
        }

        // If we made it down here, we did not know what to do, so we will
        // just throw an exception
        throw new UI_Exception('Unable to add child item.');
    }

    /**
     * Attempts to find any matching containers or components in this tree
     * using the provided query string.
     *
     * @param   mixed  The query string, or an array of query objects.
     * @return  array  All of the matching class instances.
     */
    public function query($queries)
    {
        // If a query string was passed
        if (is_string($queries)) {
            // Parse the query string and grab a query object
            $queries = UI_Query::factory($queries);
        }

        // If we have no queries to run
        if (empty($queries)) {
            // Return an empty array
            return array();
        }

        // Determine if this class instance matches the query, and if so, add
        // this class instance to the initial set of matches
        $matches = parent::query($queries);

        // Loop over each of the child items
        foreach ($this->_items as $item) {
            // Merge any returned matches with the current set of matches
            $matches = array_merge($matches, $item->query($queries));
        }

        // Return all of the matched class instances
        return $matches;
    }

    /**
     * Renders this object using the corresponding view file.
     *
     * @return  string  The rendered HTML content.
     */
    public function render()
    {
        // Create a new instance of the view class for this component
        $view = View::factory($this->_view_name);

        // Add a reference to this class instance to the view
        $view->container = $this;

        // Render the view and return the result
        return $view->render();
    }

    /**
     * Renders the HTML for each of the child items.
     *
     * @return  string  The rendered HTML content.
     */
    public function render_children()
    {
        // Define a place to store the rendered HTML
        $html = '';

        // Loop over each of the child items
        foreach ($this->_items as $item) {
            // Render the HTML for the current child item
            $html .= $item->render();
        }

        // Return all of the HTML generated by the child items
        return $html;
    }

} // End Kohana_UI_Container
